// @flow

/*
* Collapse state paths enumerable
*/
export const CollapseStatePaths = {
  COMPANY_EXTENDED: 'company_extended',
};

/**
  * Company extended field paths
  */
export const CompanyExtendedFieldPaths = {
  AUXILIARY_COMPANY_NAMES: 'auxiliaryCompanyName',
  AUXILIARY_COMPANY_NAMES_NAME: 'auxiliaryCompanyName.name',
  AUXILIARY_COMPANY_NAMES_LINE_OF_BUSINESS: 'auxiliaryCompanyName.lineOfBusiness',
  AUXILIARY_COMPANY_NAMES_EXPIRATION_DATE: 'auxiliaryCompanyName.expirationDate',
  AUXILIARY_COMPANY_NAMES_REGISTRATION_DATE: 'auxiliaryCompanyName.registrationDate',
  BUSINESS_ID: 'businessId',
  COMPANY_NAME: 'companyName',
  COMPANY_NAME_NAME: 'companyName.name',
  COMPANY_NAME_EXPIRATION_DATE: 'companyName.expidationDate',
  COMPANY_NAME_REGISTRATION_DATE: 'companyName.registrationDate',
  CONTACT_INFORMATION: 'contactInformation',
  CONTACT_INFORMATION_EMAIL: 'contactInformation.email',
  CONTACT_INFORMATION_FAX: 'contactInformation.fax',
  CONTACT_INFORMATION_HOMEPAGE: 'contactInformation.homepage',
  CONTACT_INFORMATION_PHONE: 'contactInformation.phone.number',
  CONTACT_INFORMATION_POSTAL: 'contactInformation.postal',
  CONTACT_INFORMATION_POSTAL_CITY: 'contactInformation.postal.city',
  CONTACT_INFORMATION_POSTAL_CO: 'contactInformation.postal.co',
  CONTACT_INFORMATION_POSTAL_COUNTRY: 'contactInformation.postal.country',
  CONTACT_INFORMATION_POSTAL_STREET_ADDRESS: 'contactInformation.postal.streetAddress',
  CONTACT_INFORMATION_POSTAL_ZIP_CODE: 'contactInformation.postal.zipCode',
  CONTACT_INFORMATION_VISITATION: 'contactInformation.visitation',
  CONTACT_INFORMATION_VISITATION_CITY: 'contactInformation.visitation.city',
  CONTACT_INFORMATION_VISITATION_CO: 'contactInformation.visitation.co',
  CONTACT_INFORMATION_VISITATION_COUNTRY: 'contactInformation.visitation.country',
  CONTACT_INFORMATION_VISITATION_STREET_ADDRESS: 'contactInformation.visitation.streetAddress',
  CONTACT_INFORMATION_VISITATION_ZIP_CODE: 'contactInformation.visitation.zipCode',
  DELIVERY_DATE_OF_LAST_FINANCIAL_STATEMENT: 'deliveryDateOfLastFinancialStatement',
  DOMICILE: 'domicile',
  DOMICILE_CODE: 'domicile.code',
  DOMICILE_EXPIRATION_DATE: 'domicile.expidationDate',
  DOMICILE_REGISTRATION_DATE: 'domicile.registrationDate',
  DISSOLUTION_DATE: 'dissolutionDate',
  FORM_TYPE: 'form.type',
  FORM_EXPIRATION_DATE: 'form.expirationDate',
  FORM_REGISTRATION_DATE: 'form.registrationDate',
  HISTORICAL_NAMES: 'companyName.historicalNames',
  HISTORICAL_NAMES_NAME: 'companyName.historicalNames.name',
  HISTORICAL_NAMES_EXPIRATION_DATE: 'companyName.historicalNames.expirationDate',
  HISTORICAL_NAMES_REGISTRATION_DATE: 'companyName.historicalNames.registrationDate',
  LINE_OF_BUSINESS: 'companyName.lineOfBusiness.value',
  PARALLEL_COMPANY_NAMES: 'companyName.parallelCompanyName',
  PARALLEL_COMPANY_NAMES_NAME: 'companyName.parallelCompanyName.name',
  PARALLEL_COMPANY_NAMES_EXPIRATION_DATE: 'companyName.parallelCompanyName.expirationDate',
  PARALLEL_COMPANY_NAMES_REGISTRATION_DATE: 'companyName.parallelCompanyName.registrationDate',
  REGISTRATION_DATE: 'registrationDate',
  REGISTRATION_NUMBER: 'registrationNumber',
  SHARE_CAPITAL: 'shareCapital',
  SHARE_CAPITAL_AMOUNT_OF_SHARES: 'shareCapital.amountOfShares',
  SHARE_CAPITAL_CURRENCY: 'shareCapital.currency',
  SHARE_CAPITAL_EXPIRATION_DATE: 'shareCapital.expirationDate',
  SHARE_CAPITAL_NOMINAL_VALUE: 'shareCapital.nominalValue',
  SHARE_CAPITAL_PAID_VALUE: 'shareCapital.paidValue',
  SHARE_CAPITAL_REGISTARATION_DATE: 'shareCapital.registrationDate',
  SHARE_CAPITAL_VALUE: 'shareCapital.value',
  STATE_TYPE: 'state.type',
  STATE_EXPIRATION_DATE: 'state.expirationDate',
  STATE_REGISTRATION_DATE: 'state.registrationDate',
};

/**
  * Company extended field paths
  */
export const CompanyExtendedFieldTitles = {
  AUXILIARY_COMPANY_NAMES: 'Aputoiminimet',
  AUXILIARY_COMPANY_NAMES_NAME: 'Yrityksen nimi',
  AUXILIARY_COMPANY_NAMES_LINE_OF_BUSINESS: 'Toimialakuvaus',
  AUXILIARY_COMPANY_NAMES_EXPIRATION_DATE: 'Päättymis pvm',
  AUXILIARY_COMPANY_NAMES_REGISTRATION_DATE: 'Rekisteröinti pvm',
  BUSINESS_ID: 'Y-tunnus',
  COMPANY_NAME: 'Nimitiedot',
  COMPANY_NAME_NAME: 'Yrityksen nimi',
  COMPANY_NAME_EXPIRATION_DATE: 'Päättymis pvm',
  COMPANY_NAME_REGISTRATION_DATE: 'Rekisteröinti pvm',
  CONTACT_INFORMATION: 'Yhteystiedot',
  CONTACT_INFORMATION_EMAIL: 'Sähköposti',
  CONTACT_INFORMATION_FAX: 'Faksi',
  CONTACT_INFORMATION_HOMEPAGE: 'Kotisivu',
  CONTACT_INFORMATION_PHONE: 'Puhelin',
  CONTACT_INFORMATION_POSTAL: 'Postiosoite',
  CONTACT_INFORMATION_POSTAL_CITY: 'Kaupunki',
  CONTACT_INFORMATION_POSTAL_CO: 'c/o',
  CONTACT_INFORMATION_POSTAL_COUNTRY: 'Maa',
  CONTACT_INFORMATION_POSTAL_STREET_ADDRESS: 'Katuosoite',
  CONTACT_INFORMATION_POSTAL_ZIP_CODE: 'Postinumero',
  CONTACT_INFORMATION_VISITATION: 'Käyntiosoite',
  CONTACT_INFORMATION_VISITATION_CITY: 'Kaupunki',
  CONTACT_INFORMATION_VISITATION_CO: 'c/o',
  CONTACT_INFORMATION_VISITATION_COUNTRY: 'Maa',
  CONTACT_INFORMATION_VISITATION_STREET_ADDRESS: 'Katuosoite',
  CONTACT_INFORMATION_VISITATION_ZIP_CODE: 'Postinumero',
  DELIVERY_DATE_OF_LAST_FINANCIAL_STATEMENT: 'Viimeisimmön tilinpäätöksen toimittamispvm',
  DISSOLUTION_DATE: 'Lakkaamis pvm',
  DOMICILE: 'Kotipaikka',
  DOMICILE_CODE: 'Kotipaikka',
  DOMICILE_EXPIRATION_DATE: 'Päättymis pvm',
  DOMICILE_REGISTRATION_DATE: 'Rekisteröinti pvm',
  FORM_TYPE: 'Yritysmuoto',
  FORM_EXPIRATION_DATE: 'Päättymis pvm',
  FORM_REGISTRATION_DATE: 'Rekisteröinti pvm',
  HISTORICAL_NAMES: 'Entiset nimet',
  HISTORICAL_NAMES_NAME: 'Yrityksen nimi',
  HISTORICAL_NAMES_EXPIRATION_DATE: 'Päättymis pvm',
  HISTORICAL_NAMES_REGISTRATION_DATE: 'Rekisteröinti pvm',
  LINE_OF_BUSINESS: 'Toimialakuvaus',
  PARALLEL_COMPANY_NAMES: 'Rinnakkaistoiminimet',
  PARALLEL_COMPANY_NAMES_NAME: 'Yrityksen nimi',
  PARALLEL_COMPANY_NAMES_EXPIRATION_DATE: 'Päättymis pvm',
  PARALLEL_COMPANY_NAMES_REGISTRATION_DATE: 'Rekisteröinti pvm',
  REGISTRATION_DATE: 'Rekisteröinti pvm',
  REGISTRATION_NUMBER: 'Kaupparekisterinumero',
  SHARE_CAPITAL: 'Osakepääoma',
  SHARE_CAPITAL_AMOUNT_OF_SHARES: 'Osaikkeiden lukumäärä',
  SHARE_CAPITAL_CURRENCY: 'Valuutta',
  SHARE_CAPITAL_EXPIRATION_DATE: 'Päättymis pvm',
  SHARE_CAPITAL_NOMINAL_VALUE: 'Nimellisarvo',
  SHARE_CAPITAL_PAID_VALUE: 'Maksettu',
  SHARE_CAPITAL_REGISTARATION_DATE: 'Rekisteröinti pvm',
  SHARE_CAPITAL_VALUE: 'Osakepääoma',
  STATE_TYPE: 'Yrityksen tila',
  STATE_EXPIRATION_DATE: 'Päättymispvm',
  STATE_REGISTRATION_DATE: 'Rekisteröinti pvm',
};
