import type { Action, Attributes, Methods } from "src/types";
export type PlotSearchState = {
  attributes: Attributes;
  current: PlotSearch;
  isEditMode: boolean;
  isFetching: boolean;
  isFetchingAttributes: boolean;
  list: PlotSearchList;
  collapseStates: Record<string, any>;
  isSaveClicked: boolean;
  isFormValidById: Record<string, any>;
  methods: Record<string, any>;
  planUnitAttributes: Attributes;
  planUnit: Record<string, any>;
  customDetailedPlanAttributes: Attributes;
  customDetailedPlan: CustomDetailedPlan;
  pendingCustomDetailedPlanFetches: Array<number>;
  isFetchingCustomDetailedPlanAttributes: boolean;
  pendingPlanUnitFetches: Array<number>;
  isFetchingPlanUnitAttributes: boolean;
  isFetchingSubtypes: boolean;
  subTypes: Record<string, any>;
  isFetchingForm: boolean;
  isFetchingTemplateForms: boolean;
  form: Record<string, any>;
  templateForms: Record<string, any>;
  isFetchingStages: boolean;
  stages: Array<Record<string, any>>;
  decisionCandidates: Record<string, any>;
  isBatchCreatingReservationIdentifiers: boolean;
  lastBatchReservationCreationError: any;
  isFetchingReservationIdentifierUnitLists: boolean;
  reservationIdentifierUnitLists: null | Record<string, any>;
  isCreatingDirectReservationLink: boolean;
  sectionEditorCollapseStates: Record<string, boolean>;
  relatedApplications: Array<Record<string, any>>;
  isFetchingRelatedApplications: boolean;
};
export type CustomDetailedPlan = Record<string, any>;
export type PlotSearchId = number;
export type PlotSearch = Record<string, any>;
export type PlanUnit = Record<string, any>;
export type PlotSearchList = Record<string, any>;
export type FetchSinglePlotSearchAfterEditPayload = {
  id: any;
  callbackFunctions?: Array<Record<string, any> | ((...args: Array<any>) => any)>;
};
export type ProtectedFormPathsSections = Record<string, ProtectedFormPathsSectionNode>;
export type ProtectedFormPathsSectionNode = {
  subsections?: ProtectedFormPathsSections;
  fields?: Array<string>;
  fieldChoices?: Record<string, Array<string>>;
};
export type FetchAttributesAction = Action<"mvj/plotSearch/FETCH_ATTRIBUTES", void>;
export type ReceiveAttributesAction = Action<"mvj/plotSearch/RECEIVE_ATTRIBUTES", Attributes>;
export type ReceiveMethodsAction = Action<"mvj/plotSearch/RECEIVE_METHODS", Methods>;
export type PlotSearchAttributesNotFoundAction = Action<"mvj/plotSearch/ATTRIBUTES_NOT_FOUND", void>;
export type CreatePlotSearchAction = Action<"mvj/plotSearch/CREATE", PlotSearch>;
export type EditPlotSearchAction = Action<"mvj/plotSearch/EDIT", PlotSearch>;
export type PlotSearchNotFoundAction = Action<"mvj/plotSearch/NOT_FOUND", void>;
export type FetchSinglePlotSearchAfterEditAction = Action<"mvj/plotSearch/FETCH_SINGLE_AFTER_EDIT", FetchSinglePlotSearchAfterEditPayload>;
export type DeletePlotSearchAction = Action<"mvj/plotSearch/DELETE", PlotSearchId>;
export type ReceiveIsSaveClickedAction = Action<"mvj/plotSearch/RECEIVE_SAVE_CLICKED", boolean>;
export type ReceiveFormValidFlagsAction = Action<"mvj/plotSearch/RECEIVE_FORM_VALID_FLAGS", Record<string, any>>;
export type ClearFormValidFlagsAction = Action<"mvj/plotSearch/CLEAR_FORM_VALID_FLAGS", void>;
export type FetchPlotSearchListAction = Action<"mvj/plotSearch/FETCH_ALL", string>;
export type ReceivePlotSearchListAction = Action<"mvj/plotSearch/RECEIVE_ALL", PlotSearchList>;
export type FetchSinglePlotSearchAction = Action<"mvj/plotSearch/FETCH_SINGLE", PlotSearchId>;
export type ReceiveSinglePlotSearchAction = Action<"mvj/plotSearch/RECEIVE_SINGLE", PlotSearch>;
export type HideEditModeAction = Action<"mvj/plotSearch/HIDE_EDIT", void>;
export type ShowEditModeAction = Action<"mvj/plotSearch/SHOW_EDIT", void>;
export type ReceiveCollapseStatesAction = Action<"mvj/plotSearch/RECEIVE_COLLAPSE_STATES", Record<string, any>>;
export type FetchPlanUnitAction = Action<"mvj/plotSearch/FETCH_PLAN_UNIT", Record<string, any>>;
export type ReceiveSinglePlanUnitAction = Action<"mvj/plotSearch/RECEIVE_PLAN_UNIT", PlanUnit>;
export type FetchPlanUnitAttributesAction = Action<"mvj/plotSearch/FETCH_PLAN_UNIT_ATTRIBUTES", Record<string, any>>;
export type PlanUnitAttributesNotFoundAction = Action<"mvj/plotSearch/PLAN_UNIT_ATTRIBUTES_NOT_FOUND", void>;
export type PlanUnitNotFoundAction = Action<"mvj/plotSearch/PLAN_UNIT_NOT_FOUND", void>;
export type ReceivePlanUnitAttributesAction = Action<"mvj/plotSearch/RECEIVE_PLAN_UNIT_ATTRIBUTES", Attributes>;
export type FetchCustomDetailedPlanAction = Action<"mvj/plotSearch/FETCH_CUSTOM_DETAILED_PLAN", Record<string, any>>;
export type ReceiveSingleCustomDetailedPlanAction = Action<"mvj/plotSearch/RECEIVE_CUSTOM_DETAILED_PLAN", CustomDetailedPlan>;
export type FetchCustomDetailedPlanAttributesAction = Action<"mvj/plotSearch/FETCH_CUSTOM_DETAILED_PLAN_ATTRIBUTES", Record<string, any>>;
export type CustomDetailedPlanAttributesNotFoundAction = Action<"mvj/plotSearch/CUSTOM_DETAILED_PLAN_ATTRIBUTES_NOT_FOUND", void>;
export type CustomDetailedPlanNotFoundAction = Action<"mvj/plotSearch/CUSTOM_DETAILED_PLAN_NOT_FOUND", void>;
export type ReceiveCustomDetailedPlanAttributesAction = Action<"mvj/plotSearch/RECEIVE_CUSTOM_DETAILED_PLAN_ATTRIBUTES", Attributes>;
export type FetchPlotSearchSubtypesAction = Action<"mvj/plotSearch/FETCH_PLOT_SEARCH_SUB_TYPES", void>;
export type ReceivePlotSearchSubtypesAction = Action<"mvj/plotSearch/RECEIVE_PLOT_SEARCH_SUB_TYPES", Record<string, any>>;
export type PlotSearchSubtypesNotFoundAction = Action<"mvj/plotSearch/PLOT_SEARCH_SUB_TYPES_NOT_FOUND", void>;
export type NullPlanUnitsAction = Action<"mvj/plotSearch/NULL_PLAN_UNITS", void>;
export type FormNotFoundAction = Action<"mvj/plotSearch/FORM_NOT_FOUND", Record<string, any>>;
export type FetchFormAction = Action<"mvj/plotSearch/FETCH_FORM", void>;
export type ReceiveFormAction = Action<"mvj/plotSearch/RECEIVE_FORM", Record<string, any>>;
export type EditFormAction = Action<"mvj/plotSearch/EDIT_FORM", Record<string, any>>;
export type TemplateFormsNotFoundAction = Action<"mvj/plotSearch/TEMPLATE_FORMS_NOT_FOUND", Record<string, any>>;
export type FetchTemplateFormsAction = Action<"mvj/plotSearch/FETCH_TEMPLATE_FORMS", void>;
export type ReceiveTemplateFormsAction = Action<"mvj/plotSearch/RECEIVE_TEMPLATE_FORMS", Record<string, any>>;
export type AddPlanUnitDecisionsAction = Action<"mvj/plotSearch/ADD_PLAN_UNIT_DECISIONS", Record<string, any>>;
export type RemovePlanUnitDecisionsAction = Action<"mvj/plotSearch/REMOVE_PLAN_UNIT_DECISIONS", number>;
export type ResetPlanUnitDecisionsAction = Action<"mvj/plotSearch/RESET_PLAN_UNIT_DECISIONS", void>;
export type FetchPlotSearchStagesAction = Action<"mvj/plotSearch/FETCH_PLOT_SEARCH_STAGES", Record<string, any>>;
export type ReceivePlotSearchStagesAction = Action<"mvj/plotSearch/RECEIVE_PLOT_SEARCH_STAGES", Array<Record<string, any>>>;
export type PlotSearchStagesNotFoundAction = Action<"mvj/plotSearch/PLOT_SEARCH_STAGES_NOT_FOUND", void>;
export type BatchCreateReservationIdentifiersAction = Action<"mvj/plotSearch/BATCH_CREATE_RESERVATION_IDENTIFIERS", Record<string, any>>;
export type ReservationIdentifiersCreatedAction = Action<"mvj/plotSearch/RESERVATION_IDENTIFIERS_CREATED", void>;
export type ReservationIdentifiersCreationFailedAction = Action<"mvj/plotSearch/RESERVATION_IDENTIFIERS_CREATION_FAILED", any>;
export type FetchReservationIdentifierUnitListsAction = Action<"mvj/plotSearch/FETCH_RESERVATION_IDENTIFIER_UNIT_LISTS", void>;
export type ReceiveReservationIdentifierUnitListsAction = Action<"mvj/plotSearch/RECEIVE_RESERVATION_IDENTIFIER_UNIT_LISTS", Record<string, any>>;
export type ReservationIdentifierUnitListsNotFoundAction = Action<"mvj/plotSearch/RESERVATION_IDENTIFIER_UNIT_LISTS_NOT_FOUND", void>;
export type CreateDirectReservationLinkAction = Action<"mvj/plotSearch/CREATE_DIRECT_RESERVATION_LINK", {
  data: Record<string, any>;
  callBack: (...args: Array<any>) => any;
}>;
export type DirectReservationLinkCreatedAction = Action<"mvj/plotSearch/DIRECT_RESERVATION_LINK_CREATED", void>;
export type DirectReservationLinkCreationFailedAction = Action<"mvj/plotSearch/DIRECT_RESERVATION_LINK_CREATION_FAILED", any>;
export type ClearSectionEditorCollapseStatesAction = Action<"mvj/plotSearch/CLEAR_SECTION_EDITOR_COLLAPSE_STATES", void>;
export type SetSectionEditorCollapseStateAction = Action<"mvj/plotSearch/SET_SECTION_EDITOR_COLLAPSE_STATE", {
  key: string;
  state: boolean;
}>;
export type InitializeSectionEditorCollapseStatesAction = Action<"mvj/plotSearch/INITIALIZE_SECTION_EDITOR_COLLAPSE_STATES", Record<string, boolean>>;
export type FetchPlotSearchRelatedApplicationsAction = Action<"mvj/plotSearch/FETCH_RELATED_APPLICATIONS", number>;
export type ReceivePlotSearchRelatedApplicationsAction = Action<"mvj/plotSearch/RECEIVE_RELATED_APPLICATIONS", Array<Record<string, any>>>;
export type PlotSearchRelatedApplicationsNotFoundAction = Action<"mvj/plotSearch/RELATED_APPLICATIONS_NOT_FOUND", any>;