import type { Attributes, Methods } from "types";
import type { LeaseId } from "@/leases/types";
import type { Contact } from "@/contacts/types";
import type { ServiceUnit } from "@/serviceUnits/types";
export type InvoiceState = {
  attributes: Attributes;
  byLease: InvoiceListMap;
  invoiceToCredit: ContentInvoice | null | undefined;
  isCreateClicked: boolean;
  isCreatePanelOpen: boolean;
  isCreditClicked: boolean;
  isCreditPanelOpen: boolean;
  isEditClicked: boolean;
  isFetching: boolean;
  isFetchingAttributes: boolean;
  isSaving: boolean;
  methods: Methods;
  patchedInvoice: Invoice | null | undefined;
};
export type Invoice = {
  id: InvoiceId;
  lease: LeaseId;
  number?: number;
  recipient: Contact;
  type: string;
  rows: Array<Record<string, any>>;
  payments: Array<Record<string, any>>;
  credit_invoices: Array<Record<string, any>>;
  interest_invoices: Array<Record<string, any>>;
  created_at: string;
  modified_at: string;
  sent_to_sap_at?: string;
  sap_id?: string;
  due_date: string;
  adjusted_due_date?: string;
  invoicing_date?: string;
  state: string;
  billing_period_start_date?: string;
  billing_period_end_date?: string;
  postpone_date?: string;
  total_amount: number;
  billed_amount: number;
  outstanding_amount?: number;
  payment_notification_date?: string;
  collection_charge?: number;
  notes: string;
  generated: boolean;
  description?: string;
  invoiceset?: number;
  credited_invoice?: number;
  interest_invoice_for?: number;
  payment_notification_catalog_date?: string;
  delivery_method?: string;
  service_unit: ServiceUnit;
};
export type ContentInvoice = {
  id: InvoiceId;
  lease?: LeaseId;
  number?: number;
  recipient: number;
  recipientFull: Contact;
  rows: Array<Record<string, any>>;
  sent_to_sap_at?: string;
  sap_id?: string;
  due_date: string;
  adjusted_due_date?: string;
  invoicing_date?: string;
  state: string;
  billing_period_end_date?: string;
  billing_period_start_date?: string;
  postpone_date?: string;
  total_amount: number;
  billed_amount: number;
  payments: Array<Record<string, any>>;
  outstanding_amount?: number;
  payment_notification_date?: string;
  collection_charge?: number;
  payment_notification_catalog_date?: string;
  delivery_method?: string;
  type: string;
  notes: string;
  generated: boolean;
  description?: string;
  totalShare: number | null | undefined;
  receivableTypes: Array<Record<string, any>>;
  credit_invoices: Array<Record<string, any>>;
  credited_invoice?: number;
  interest_invoices: Array<Record<string, any>>;
  interest_invoice_for?: number;
  invoiceset?: number;
  tableGroupName?: string;
};
export type InvoiceId = number;
export type InvoiceList = Array<Invoice>;
export type InvoiceListMap = Record<string, any>;
export type ExportInvoiceToLaskeAndUpdateListPayload = {
  id: InvoiceId;
  lease: LeaseId;
};
export type InvoicePayload = {
  id?: InvoiceId;
  lease?: LeaseId;
  due_date: string;
  billing_period_start_date?: string;
  billing_period_end_date?: string;
  postpone_date?: string;
  notes: string;
  payments?: Array<Record<string, any>>;
  rows: Array<Record<string, any>>;
  type?: string;
  tenant?: number | "all";
  recipient?: number;
};
export type NewInvoice = {
  lease: LeaseId;
  tenant: number | "all";
  recipient?: number;
  type?: string;
  due_date: string;
  billing_period_start_date?: string;
  billing_period_end_date?: string;
  notes: string;
  rows: Array<Record<string, any>>;
};
export type CreditInvoice = {
  amount: number;
  notes: string;
  receivable_type: string;
  type: string;
};
export type CreditInvoicePayload = {
  creditData: Record<string, any>;
  invoiceId: InvoiceId;
  lease: LeaseId;
};
