// @flow

/**
 * Users permissions enumerable.
 *
 * @type {{}}
 */
export const UsersPermissions = {
  VIEW_LEASE: 'view_lease',
  ADD_RELATEDLEASE: 'add_relatedlease',
  DELETE_RELATEDLEASE: 'delete_relatedlease',
  CHANGE_LEASE_LEASE_AREAS: 'change_lease_lease_areas',
  VIEW_LEASE_LEASE_AREAS: 'view_lease_lease_areas',
  ADD_LEASEAREA: 'add_leasearea',
  DELETE_LEASEAREA: 'delete_leasearea',
  ADD_LEASEAREAADDRESS: 'add_leaseareaaddress',
  DELETE_LEASEAREAADDRESS: 'delete_leaseareaaddress',
  ADD_PLANUNIT: 'add_planunit',
  DELETE_PLANUNIT: 'delete_planunit',
  ADD_PLOT: 'add_plot',
  DELETE_PLOT: 'delete_plot',
  ADD_TENANT: 'add_tenant',
  DELETE_TENANT: 'delete_tenant',
  ADD_TENANTCONTACT: 'add_tenantcontact',
  DELETE_TENANTCONTACT: 'delete_tenantcontact',
  CHANGE_LEASE_IS_RENT_INFO_COMPLETE: 'change_lease_is_rent_info_complete',
  ADD_RENT: 'add_rent',
  DELETE_RENT: 'delete_rent',
  CHANGE_RENT_DUE_DATES: 'change_rent_due_dates',
  ADD_FIXEDINITIALYEARRENT: 'add_fixedinitialyearrent',
  DELETE_FIXEDINITIALYEARRENT: 'delete_fixedinitialyearrent',
  ADD_CONTRACTRENT: 'add_contractrent',
  DELETE_CONTRACTRENT: 'delete_contractrent',
  ADD_RENTADJUSTMENT: 'add_rentadjustment',
  DELETE_RENTADJUSTMENT: 'delete_rentadjustment',
  ADD_LEASEBASISOFRENT: 'add_leasebasisofrent',
  DELETE_LEASEBASISOFRENT: 'delete_leasebasisofrent',
  ADD_DECISION: 'add_decision',
  DELETE_DECISION: 'delete_decision',
  ADD_CONDITION: 'add_condition',
  DELETE_CONDITION: 'delete_condition',
  ADD_CONTRACT: 'add_contract',
  DELETE_CONTRACT: 'delete_contract',
  ADD_CONTRACTCHANGE: 'add_contractchange',
  DELETE_CONTRACTCHANGE: 'delete_contractchange',
  ADD_COLLATERAL: 'add_collateral',
  DELETE_COLLATERAL: 'delete_collateral',
  ADD_INSPECTION: 'add_inspection',
  DELETE_INSPECTION: 'delete_inspection',
  ADD_EMAILLOG: 'add_emaillog',
  VIEW_EMAILLOG: 'view_emaillog',
  ADD_CONSTRUCTABILITYDESCRIPTION: 'add_constructabilitydescription',
  DELETE_CONSTRUCTABILITYDESCRIPTION: 'delete_constructabilitydescription',
  ADD_LEASEAREAATTACHMENT: 'add_leaseareaattachment',
  DELETE_LEASEAREAATTACHMENT: 'delete_leaseareaattachment',
  CHANGE_LEASE_IS_INVOICING_ENABLED: 'change_lease_is_invoicing_enabled',
  VIEW_INVOICE: 'view_invoice',
  ADD_INVOICE: 'add_invoice',
  VIEW_INVOICESET: 'view_invoiceset',
  VIEW_INVOICENOTE: 'view_invoicenote',
  ADD_COLLECTIONLETTER: 'add_collectionletter',
  VIEW_COLLECTIONLETTER: 'view_collectionletter',
  VIEW_CONTACT: 'view_contact',
  ADD_INFILLDEVELOPMENTCOMPENSATIONLEASE: 'add_infilldevelopmentcompensationlease',
  DELETE_INFILLDEVELOPMENTCOMPENSATIONLEASE: 'delete_infilldevelopmentcompensationlease',
  ADD_INFILLDEVELOPMENTCOMPENSATIONDECISION: 'add_infilldevelopmentcompensationdecision',
  DELETE_INFILLDEVELOPMENTCOMPENSATIONDECISION: 'delete_infilldevelopmentcompensationdecision',
  ADD_INFILLDEVELOPMENTCOMPENSATIONINTENDEDUSE: 'add_infilldevelopmentcompensationintendeduse',
  DELETE_INFILLDEVELOPMENTCOMPENSATIONINTENDEDUSE: 'delete_infilldevelopmentcompensationintendeduse',
  ADD_BASISOFRENTPROPERTYIDENTIFIER: 'add_basisofrentpropertyidentifier',
  DELETE_BASISOFRENTPROPERTYIDENTIFIER: 'delete_basisofrentpropertyidentifier',
  ADD_BASISOFRENTDECISION: 'add_basisofrentdecision',
  DELETE_BASISOFRENTDECISION: 'delete_basisofrentdecision',
  ADD_BASISOFRENTRATE: 'add_basisofrentrate',
  DELETE_BASISOFRENTRATE: 'delete_basisofrentrate',
  EDIT_GLOBAL_UI_DATA: 'edit_global_ui_data',
};
