export const purposeOptions = [
  {value: '100', display_name: 'Asuminen / yleinen'},
  {value: '101', display_name: 'Vapaarahoitteisia omistusasuntoja'},
  {value: '102', display_name: 'Aravaomistusasuntoja'},
  {value: '103', display_name: 'Vapaarahoitteisia vuokra-asuntoja'},
  {value: '104', display_name: 'Aravavuokrataloja'},
  {value: '105', display_name: 'Peruskorjattuja arava-vuokrataloja'},
  {value: '106', display_name: 'Omakotitalo'},
  {value: '107', display_name: 'Paritalo'},
  {value: '108', display_name: 'Sekatalo'},
  {value: '109', display_name: 'Asumisoikeusasuntoja'},
  {value: '110', display_name: 'Opiskelija-asuntoja'},
  {value: '111', display_name: 'Vanhusten asuntoja'},
  {value: '112', display_name: 'Palvelutalo/hoitokoti'},
];
