export const purposeOptions = [
  {value: '100', label: 'Asuminen / yleinen'},
  {value: '101', label: 'Vapaarahoitteisia omistusasuntoja'},
  {value: '102', label: 'Aravaomistusasuntoja'},
  {value: '103', label: 'Vapaarahoitteisia vuokra-asuntoja'},
  {value: '104', label: 'Aravavuokrataloja'},
  {value: '105', label: 'Peruskorjattuja arava-vuokrataloja'},
  {value: '106', label: 'Omakotitalo'},
  {value: '107', label: 'Paritalo'},
  {value: '108', label: 'Sekatalo'},
  {value: '109', label: 'Asumisoikeusasuntoja'},
  {value: '110', label: 'Opiskelija-asuntoja'},
  {value: '111', label: 'Vanhusten asuntoja'},
  {value: '112', label: 'Palvelutalo/hoitokoti'},
];
