on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    
name: Sonarcloud Scan
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=managedcloudapplications
          -Dsonar.projectKey=mvj-ui
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}